# PostgreSQL. Versions 8.2 and up are supported.
#
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: itp-processor_development
  #username: itp-processor
  #password:
  #host: localhost
  #port: 5432
  #schema_search_path: myapp,sharedapp,public
  #min_messages: notice

test:
  <<: *default
  database: itp-processor_test

production:
  <<: *default
  database: itp-processor_production
  username: itp-processor
  password: <%= ENV['ITP-PROCESSOR_PASSWORD'] %>
